AWSTemplateFormatVersion: '2010-09-09'
Description: Same-account self-managed CloudFormation StackSet roles

Parameters:
  BootstrapBucketPrefix:
    Type: String
    AllowedPattern: '^[a-z0-9-]+$'

Resources:
  AdministrationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSCloudFormationStackSetAdministrationRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: {Service: cloudformation.amazonaws.com}
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AssumeStackSetExecutionRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sts:AssumeRole
                Resource: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/AWSCloudFormationStackSetExecutionRole'
  ExecutionRole:
    Type: AWS::IAM::Role
    DependsOn: AdministrationRole
    Properties:
      RoleName: AWSCloudFormationStackSetExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/AWSCloudFormationStackSetAdministrationRole'
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Policies:
        - PolicyName: ReadPrivateStackSetAssets
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: s3:GetObject
                Resource: !Sub 'arn:${AWS::Partition}:s3:::${BootstrapBucketPrefix}-${AWS::AccountId}-*-bootstrap/assets/*'

Outputs:
  AdministrationRoleArn: {Value: !GetAtt AdministrationRole.Arn}
  ExecutionRoleName: {Value: !Ref ExecutionRole}
